### ISSUE TITLE
Use logo colors as inspiration for theme colors

### ISSUE THREAD

**Issue by jdleonard** [Drupal-NYC/drupalcampnyc#104]

**Comment by jdleonard** [comment]
@ccaajj You haven't committed the color changes yet, right?

**Comment by ccaajj** [comment]
Not yet. Meant to get logo.svg implemented as well, but still waiting on final version of the svg. Right now it's using dcnyc2020-logo.png as a placeholder.

**Comment by ccaajj** [comment]
Just did two commits, (1) using new colors in header blend and adding logo animation on home page, and (2) displaying logo.svg in header via img tag instead of background-image

Can you grab these changes, or do I need to do a pull request?

**Comment by jdleonard** [comment]
Looking good!
