### ISSUE TITLE
Sponsorship packages table can't be scrolled

### ISSUE THREAD

**Issue by vgrozdanoski** [Drupal-NYC/drupalcampnyc#122]
we should check the responsiveness of the sponsorship packages. Currently, the sponsorship table can't be scrolled left and right.

**Comment by pbone** [comment]
I'll work on making these tables responsive

**Comment by pbone** [comment]
pulled into master

**Comment by jdleonard** [comment]
Looking good! Remember that you can add "Fixes #122" as a commit message and that would close the issue upon merge to master.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/drupalnyc/issues/3183357
