### ISSUE TITLE
Add Mailchimp sign up form

### ISSUE THREAD

**Issue by jdleonard** [Drupal-NYC/drupalcampnyc#151]
Two locations:

1. Footer (white area, centered, all pages)
2. Homepage call to action button "Get Updates", leading to a dedicated sign up page.

**Comment by vgrozdanoski** [comment]
I can add a popup for the Subscribe for Updates button instead of linking it to a different signup page. I need to add a script in the <head> section to do so. Should we do this?

**Comment by jdleonard** [comment]
Great idea! But I'd suggest adding the JavaScript needed via code (git) and just adding a css class name that causes a button to have the desired behavior. That way we can easily add the button wherever we want within site contact. I'd avoid some JavaScript as content within a paragraph.

**Comment by vgrozdanoski** [comment]
Yes, that's the way, adding code in the <head> section so Mailvhimp would be able to trigger the popup

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/drupalnyc/issues/3186101
