### ISSUE TITLE
Misc Homepage fixes

### ISSUE THREAD

**Issue by pbone** [Drupal-NYC/drupalcampnyc#155]
- Move CTA buttons out of the hero, add two more in a content row under hero
- Crop and compress home page hero image
- Add credits for logo and image
- Add "Friday, Nov 13, Saturday, Nov 14, Virtual Conference in top header-nav area

**Comment by jdleonard** [comment]
![image](https://user-images.githubusercontent.com/2074112/90195764-4fb12b80-dd98-11ea-9327-82148562ac41.png)

@pbone We should vertically center the slogan on mobile, right?
