### ISSUE TITLE
Update readme with Apple M1 Instructions

### ISSUE THREAD

**Issue by latoyale** [Drupal-NYC/drupalcampnyc#186]
Updated the readme on my branch with the Apple M1 instructions for setting up the local environment.
Instructions are:
*** If you are using an Apple laptop with the M1 chip, make sure you have this version of PHP installed: PHP 7.3.27 You can check your version by using : php -v. Do not upgrade to PHP 8.0! The installation of the environment for M1 will not work with that version.

*** If you are running laptop with the Apple M1 chip please note: the lando installation will also install Docker for the intel chip. This will cause an error on your machine. You must install the M1 version of Docker. This should overwrite the one installed by Lando. It can be found here: (https://desktop.docker.com/mac/stable/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-arm64).

If you find that you can see the site, but the theme was not applied, check out your error/warning messages in the console. You may be asked to install a module called optipng. Use this command to install it: npm install --save optipng-bin

**Comment by latoyale** [comment]
updated the read me file

**Comment by jdleonard** [comment]
@latoyale Be sure to open a pull request from your 186- branch to main so we can get this in!
