### ISSUE TITLE
Update footer and misc. instances of 2020 to 2021

### ISSUE THREAD

**Issue by jdleonard** [Drupal-NYC/drupalcampnyc#198]

**Comment by jdleonard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update footer and misc. instances of 2020 to 2021](https://trello.com/c/LtcCWGt8/97-update-footer-and-misc-instances-of-2020-to-2021)

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/drupalnyc/issues/3221581
