### ISSUE TITLE
Page header markup should not be duplicated

### ISSUE THREAD

**Issue by jdleonard** [Drupal-NYC/drupalcampnyc#84]
```html
<header role="banner" class="page--header">
```
and 
```html
<header class="mobile--page--header">
```
are present on all pages, but contain identical markup (the mobile version also contains some empty hamburger-menu tags).

The duplicate markup results in some element IDs being duplicated (e.g. "block-drupaleurope-branding").

Solution: output the header markup once and style it differently for mobile/desktop using media queries.

**Comment by ccaajj** [comment]
When I add the new logo (colorful allcaps DCNYC202 version) I'll look into this too

**Comment by pbone** [comment]
div ids weren't necessary for branding block, or navs for any CSS/JS functionality, so I removed them.

**Comment by jdleonard** [comment]
I guess for performance and maintainability, is it easy enough to output the identical markup once rather than twice?

**Comment by pbone** [comment]
getting viewport info into twig would be tough. Should I look into that?

page--node.html.twig writes out both:
header.page--header
header.mobile--page--header

and sticks the region  {{ page.header }} into both
then they're hidden/revealed with CSS media queries.

I realize my fix wasn't necessarily what you asked for, but there are no longer clashing ids.
Is it worth keeping?

**Comment by jdleonard** [comment]
Your fix definitely improves things!

Frontend is my weak suit so please forgive me...

I'm not sure what "getting viewport info into twig" means, but I would think that the only change in Twig would be to not output "header.mobile--page--header" at all.

Then, could the old CSS for "header.page--header" and "header.mobile--page--header" be wrapped in a media query so that only the appropriate CSS is applied to "header.mobile--page--header" (the only remaining class)?

**Comment by pbone** [comment]
I think you're right JD, I redid this with jquery, one header, swapping out classes based on screen size.

**Comment by jdleonard** [comment]
@pbone I'm having trouble seeing what you changed because of all the formatting changes. Could I trouble you to revert this and commit just the substantive changes?

**Comment by jdleonard** [comment]
Hmm, I wonder if there isn't a cleaner fix that doesn't involve JS. Can we just put the CSS definitions in a media query and not touch the DOM?

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/drupalnyc/issues/3182843
