### ISSUE TITLE
Replace logo with refined final logo

### ISSUE THREAD

**Issue by jdleonard** [Drupal-NYC/drupalcampnyc#89]
When available...

**Comment by ccaajj** [comment]
Hoping to get this and other header/logo fixes done over this long weekend

**Comment by jdleonard** [comment]
Final logos are now available in various sizes in the "Camp Logo" folders at https://drive.google.com/drive/u/1/folders/1PltSDfvvrocj4Pu9018w27dZKMPjNVFh
