### ISSUE TITLE
Header is smushed when logged in at < 1024px browser width

### ISSUE THREAD

**Issue by jdleonard** [Drupal-NYC/drupalcampnyc#91]
![image](https://user-images.githubusercontent.com/2074112/82721794-b853a500-9c8e-11ea-84d8-e43c1b40ae2c.png)

![image](https://user-images.githubusercontent.com/2074112/82721808-e20ccc00-9c8e-11ea-99db-ace6e7750e3a.png)

**Comment by ccaajj** [comment]
Will fix as I add the new DCNYC2020 logo

**Comment by jdleonard** [comment]
No longer an issue with the new drupalnyc theme
