### ISSUE TITLE
Create sponsor detail pages and link to from sponsor logos

### ISSUE THREAD

**Issue by jdleonard** [Drupal-NYC/drupalcampnyc#92]

**Comment by jdleonard** [comment]
Please see this branch for the config changes I already made https://github.com/Drupal-NYC/drupalcampnyc/tree/92-sponsor-detail-pages

**Comment by jdleonard** [comment]
Some sample sponsor logos for testing: https://drive.google.com/open?id=17iPIhXi61NySSM-B99sQwv2oSRiENVF0&authuser=jd%40jdleonard.net&usp=drive_fs

**Comment by vgrozdanoski** [comment]
Ready for styling.

@pbone all sponsor views-row have div classes with the sponsor level respectively.
For ex:
The div inside of views-row of the Venue Sponsor block has "sponsor-venue" class, Community sponsor has "sponsor-community" class etc.

We can try to make some improvements on the detailed sponsor page (node). Maybe style the website link like a button or similar. That's up to you.
Currently, the svg is displayed with 400px height from the field settings, I can increase/decrease that or remove it if you want to control it from css.

Branch https://github.com/Drupal-NYC/drupalcampnyc/tree/141-sponsor-detail-pages-update

**Comment by pbone** [comment]
Is this up on dev? I tried to pull data from dev but I'm not sure if it was there.

**Comment by jdleonard** [comment]
@pbone No, it's just in the branch that @vgrozdanoski linked to. We should keep master in a ready-to-deploy state so nothing should be merged there until it has been reviewed.

**Comment by jdleonard** [comment]
@pbone Note also that for the Sponsors Page (/sponsors) this branch requires the use of the paragraph type that lets you choose a view (Sponsors) to display rather than the Element List - Sponsors paragraph type.

**Comment by jdleonard** [comment]
@pbone I just wanted to make sure that you saw my last comment here - it looks like you might have themed the "Element List - Sponsors" paragraph type, which is no longer in use in branch 141-sponsor-detail-pages-update ( https://github.com/Drupal-NYC/drupalcampnyc/pull/142 ).

Also, for accessibility and consistency with other pages, would you please ensure that the sponsor detail pages have an <h1> heading with the sponsor name? Thanks!

**Comment by pbone** [comment]
"Sponsors Page (/sponsors) this branch requires the use of the paragraph type that lets you choose a view (Sponsors) to display rather than the Element List - Sponsors paragraph type."

@vgrozdanoski did this part already

h1 title addded, to branch 141-sponsor-detail-pages-update

**Comment by jdleonard** [comment]
@pbone Thanks!

Looks like we might need some more theming love for the sponsor logos on the Sponsors page to ensure that logos at the same level are comparable in size (maybe there should be both a max width and a max height for each sponsor type? And we should probably hide the duplicative sponsor type label from the view.

![image](https://user-images.githubusercontent.com/2074112/87218621-7526c180-c322-11ea-82e2-796f58c04f41.png)

**Comment by vgrozdanoski** [comment]
Just to clarify: `Element List - Sponsors `is not a Paragraph type but `Preselect View Option` in the Sponsor Paragraph type fields

**Comment by pbone** [comment]
When sponsor view blocks are added as paragraphs (like the /sponsors page).
and the display of:

**Block Venue
Block Diamond
Block Platinum
Block Gold
Block Homegrown
Block Community
Block Tri-State**

is chosen, any sponsor nodes flagged as such will have their logo image shown in that block view, and linked to its sponsor node.

To apply the unique sizing and flex alignment classes for each of these sections, 
under **> Options**, expand to show the **Argument** field and add:

**Venue
Diamond
Platinum
Gold
Homegrown
Community
Tri-State**

_(name corresponding to the selected block display - not case sensitive)_

**Comment by jdleonard** [comment]
@pbone I don't see an Options or Argument field for the "Element - Views block" (Sponsors view). Is there some missing configuration or have I misunderstood how to get the styling to take? I have a feeling I'm doing something wrong :)

![image](https://user-images.githubusercontent.com/2074112/87238798-4a497580-c3d5-11ea-93be-13e7e5a4179c.png)

**Comment by pbone** [comment]
Here's a screenshot of mine below. I'd delete that whole paragraph and start over?

![screencapture-drupalcampnyc-lndo-site-node-5-edit](https://user-images.githubusercontent.com/3978195/87260464-0f504c00-c480-11ea-9339-b453872172b0.png)

**Comment by jdleonard** [comment]
Okay so apparently the problem was that I was using "Element - Views block" and then selecting "Sponsors" rather than using "Element - Sponsor" and then selecting "Sponsors".

Theming looks good to me!

I created #143 to track improving the process of adding a paragraph to list sponsors.

Merged to master.

**Comment by jdleonard** [comment]
I created #144 to track the need to re-create the content on the Sponsors page.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/drupalnyc/issues/3182854
